CREATE TABLE users 
(
  id SERIAL NOT NULL,
  address CHARACTER VARYING(256) UNIQUE NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  updated TIMESTAMP NOT NULL DEFAULT NOW(),
  created TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
CREATE TABLE categories
(
  id serial NOT NULL,
  address CHARACTER VARYING(256) UNIQUE NOT NULL,
  name CHARACTER VARYING(256),
  url CHARACTER VARYING(256),
  img_url TEXT,
  description TEXT,
  active BOOLEAN DEFAULT TRUE,
  updated TIMESTAMP NOT NULL DEFAULT NOW(),
  created TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
CREATE TABLE tokens
(
  id serial NOT NULL,
  address CHARACTER VARYING(256) NOT NULL,
  name CHARACTER VARYING(256),
  img_url CHARACTER VARYING(256),
  description TEXT,
  owner INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  category INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  metadata JSONB,
  active BOOLEAN DEFAULT TRUE,
  updated TIMESTAMP NOT NULL DEFAULT NOW(),
  created TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
CREATE TABLE ERC20Tokens (
  id serial NOT NULL,
  address CHARACTER VARYING(256) NOT NULL,
  decimal INTEGER NOT NULL,
  name CHARACTER VARYING(256),
  symbol CHARACTER VARYING(256),
  icon CHARACTER VARYING(256),
  active BOOLEAN DEFAULT TRUE,
  updated TIMESTAMP NOT NULL DEFAULT NOW(),
  created TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
CREATE TABLE ERC20TokenAddresses (
  id serial NOT NULL,
  chain_id CHARACTER VARYING(20) NOT NULL,
  address CHARACTER VARYING(256) NOT NULL,
  token  INTEGER NOT NULL REFERENCES ERC20Tokens(id) ON DELETE CASCADE,
  active BOOLEAN DEFAULT TRUE,
  updated TIMESTAMP NOT NULL DEFAULT NOW(),
  created TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
CREATE TABLE categoryAddresses (
  id serial NOT NULL,
  chain_id CHARACTER VARYING(20) NOT NULL,
  address CHARACTER VARYING(256) NOT NULL,
  category  INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  active BOOLEAN DEFAULT TRUE,
  updated TIMESTAMP NOT NULL DEFAULT NOW(),
  created TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
CREATE TABLE orders
(
  id serial NOT NULL,
  maker_token INTEGER NOT NULL REFERENCES tokens(id),
  taker_token INTEGER NOT NULL REFERENCES ERC20Tokens(id) ,
  maker_amount DECIMAL NOT NULL,
  taker_amount DECIMAL,
  maker_address INTEGER NOT NULL REFERENCES users(id),
  taker_address INTEGER REFERENCEvalidS users(id),
  min_price DECIMAL NOT NULL,
  type CHARACTER VARYING(20) NOT NULL,
  status INTEGER DEFAULT 0,
  expiry_date TIMESTAMP,
  txHash CHARACTER VARYING(256),
  signature CHARACTER VARYING(256),
  views INTEGER DEFAULT 0,
  active BOOLEAN DEFAULT TRUE,
  updated TIMESTAMP NOT NULL DEFAULT NOW(),
  created TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
CREATE TABLE bids
(
  id serial NOT NULL,
  orders INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  users INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  price DECIMAL NOT NULL,
  status INTEGER DEFAULT 0,
  active BOOLEAN DEFAULT TRUE,
  updated TIMESTAMP NOT NULL DEFAULT NOW(),
  created TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
CREATE TABLE favorites
(
  id SERIAL NOT NULL,
  token INTEGER NOT NULL REFERENCES tokens(id) ON DELETE CASCADE,
  users INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  updated TIMESTAMP NOT NULL DEFAULT NOW(),
  created TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY(id)
);